### ISSUE TITLE
Update doc for non-TCP passthrough ingress controller

### ISSUE THREAD

**Issue by tilleryd** [DecipherNow/helm-charts#387]
Our docs assume we use Voyager for ingress into the mesh and leave it at that. However, if a customer chooses to use something like Nginx, a non-TCP passthrough that supports SNI, then there a few steps we should document.

1. Create a TLS secret https://kubernetes.io/docs/concepts/services-networking/ingress/#tls
2. Apply Nginx YAML using TLS secret https://www.nginx.com/products/nginx/kubernetes-ingress-controller

**Comment by chrisbsmith** [comment]
@tilleryd i believe that we have discussed that this issue is not 100% accurate. Since the edge expects to do SSL termination, any ingress controller (Nginx or voyager) needs to be configured for ssl-passthrough. 
Additionally, our Proxy does not expect the certificates in this format. Instead it wants a reference to the ca, cert and key individually.

**Comment by tilleryd** [comment]
@chrisbsmith Yes, this was a misunderstanding on my part when I wrote the issue.

**Comment by chrisbsmith** [comment]
👍
