### ISSUE TITLE
Proposal: Propose a solution to decompose the Grey Matter Helm charts

### ISSUE THREAD

**Issue by chrisbsmith** [DecipherNow/helm-charts#422]
This issue should drive research into decomposing the Grey Matter Helm charts into more manageable and a simplified installation. This can include the separation of Fabric (the actual mesh - Control, Control API, Proxy), Sense (Dashboard, SLO, etc) and Data (Data, JWT).  This should drive issues for work in future sprints.

**Comment by whenhellfreezes** [comment]
I had some success decomposing a database and application with https://github.com/roboll/helmfile . We have talked about it before but putting it up on github for visibility.

**Comment by chrisbsmith** [comment]
It's also highly likely that any chart decomposition will greatly increase the ease of upgrades.

**Comment by hiromis** [comment]
> It's also highly likely that any chart decomposition will greatly increase the ease of upgrades.

@chrisbsmith Would you mind sharing what kind of difficulties you went through upgrading/rolling back grey matter in DI2E environment today?

**Comment by hiromis** [comment]
## Helm chart decomposition brainstorming

#### Consider separating each project's chart to its code repository

Currently, each project's chart is in its respective folder living in `helm-chart` repository. What if we put the chart in the service's code repository just like we do with Dockerfile? 

Scenario:

When upgrading gm-control under https://github.com/DecipherNow/helm-charts/issues/389, the 1.1.0 release has been "out" since Nov 4th. Developers knew one of the values (`cipher_filter`) needs to be removed from `gm-control-api/json/services/cluster.json` when they introduced the code that required that change. This was brought up when DHS was installing the new version of gm-control-api right after the release, but it was forgotten once that was done. 3 weeks later, we were ready to upgrade the helm-chart repo, but updating the version numbers resulted in an error `[error] Stream 10, type.googleapis.com/envoy.api.v2.Cluster: Error Code INTERNAL, Message “Failed to initialize cipher suites EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH. The following ciphers were rejected when tried individually: EDH, EDH”` which needed to be investigated and resolved all over.



Some of the advantages of having the service's helm chart closer to the source code:

* **Ease of versioning charts** - Just like in the above case, when a chart needs to be changed due to the code change (e.g. environment variable addition, removal, etc), the versioning of the chart is directly tied to the code. When it's time to update the overall mesh chart, all we need to do should be to point to the newer version of the chart for that service. Making chart changes due to code change is a developer's responsibility.
* **CI can continue to push new versions of a chart to Nexus when a service is released (or on push to the default branch, or every commits if desired)** - We do this with docker images already. When a service is released, we should be able to push a corresponding Helm chart even if the overall greymatter mesh is not ready to use that version yet. This will make easier for developers to do integration tests as all they need to do is to grab the greymatter mesh Helm chart and point the service of the interest to point to the one that was just released.
* **When a service become obsolete, helm chart gets deleted when the code repo is deleted** - No orphan helm charts for services that are no longer there.
* **Forces isolation of charts** - Helm documentation states that each chart (even sub charts) should be stand-alone. When we separate them, we forces each to be stand-alone. 

Disadvantage:

* The flip side of the first advantage is that changes that SRE team wants to be aware of may fall through the crack (like removal of `cipher_filter`). A process may need to be in place so that all the changes that went into the release appears in change log.

**Comment by hiromis** [comment]
### Consider the removal of greymatter*.yaml files

I am not sure why we chose to have "custom" files, so please let me know if I am missing something. I believe, by default, GreyMatter chart version 2.2.0, say, should contain all the default values in its `values.yaml` file except for minimally and absolutely required things like Nexus credentials and maybe an environment (`openshift` vs.` kubernetes`). We already have a nice `make credentials` that generates `credentials.yaml` which asks users questions that need to be answered. Why not expand that just a little bit so that a user can type in all the necessary answers which generates one file which will then be sent to the `helm install` command? This will simplify the installation greatly, and if there are issues, there are not as many variations in custom files that can make installations different. If we need non-default certificates or non-default configuration for a particular customer, then those should be considered as "customization".  By default, we should be able to install the basic service mesh - no overwrites or customizations. 


#### Scenario:

Here are how many times we define "version" like things for gm-control:

**control/Chart.yaml**

```
apiVersion: v1
appVersion: 1.1.0
...
version: 2.1.3
```



**control/values.yaml**

```
global:
	control:
    	version: 1.1.0
control:
    image: 'docker.production.deciphernow.com/deciphernow/gm-control:{{ $.Values.global.control.version }}'
```



**greymatter/requirements.yaml**

```
  - name: control
    repository: 'https://nexus.production.deciphernow.com/repository/helm-hosted'
    version: '2.1.3'
```



**greymatter/values.yaml**

	global:
		control:
			version: 1.1.0



**greymatter.yaml**

	global:
		control:
	    	version: 1.1.0
	
	control:
		control:
	    	image: docker.production.deciphernow.com/deciphernow/gm-control:1.1.0

All we want is to use gm-control 1.1.0 image and all the appropriate Kubernettes configurations for that release, but there are so many places that can go wrong. 



Some ideas for simplification here are:

* Allow control's chart to choose the appropriate Docker image tag.
* From greymatter (the umbrella chart), only select the chart version of `control`.
* Remove the version from global scope. If another child service needs to know the version of `control` then we can create a global variable in `greymatter/values.yaml` that will simply read the docker tag of gm-control in the denendant `control` chart. `control` chart will likely be mismatch if a parent forces it to use `1.0.8`, for example. A given chart is specific to the particular tag of Docker image, so better to prevent mismatch by not giving them a way to set it (e.g. via global variable).
* Delete greymatter.yaml



#### Advantage:

* **Simple ([KISS](https://en.wikipedia.org/wiki/KISS_principle))** - I believe above scenario explains it. Simple is good.

**Comment by chrisbsmith** [comment]
I agree that the greymatter.yaml file has gotten overly complex and bloated. The majority of config options can probably be moved to the greymatter/values.yaml file. 

While I like the idea of removing most options and delegating they to the sub chart, a lot of the data in the greymatter.yaml file is there because it’s shared between multiple sub charts, specifically content under .global.  When we looking to bring this separation, we are going to have to be very diligent to ensure we understand what each option does and the cascading impact it could potentially have on other value templates. 

Even when we break up the charts, there will be common values that need to be shared amongst all Grey Matter components , like the control address and port number. 

I’m all for this work, but want to make sure we approach it gingerly.

**Comment by hiromis** [comment]
Absolutely! I also believe it is important to carefully consider what's in global scope and we document why they are there.

**Comment by chrisbsmith** [comment]
💯 our documentation is super weak sauce right now

**Comment by chrisbsmith** [comment]
If only I knew the developer. 🤦‍♂️

**Comment by hiromis** [comment]
### Consider creating a "common" chart

`_envvars.tpl` and `_helpers.tpl` are copied to each subchart's `templates/`

folder with minor variations. These partials will also be useful for "user services" (the services our customers will deploy to the mesh). So having a Grey Matter common/utility which can simply be added as a dependency would not only prevent us from copying the same definitions repeatedly, but also allows customers to take advantage of what we've already created .

https://medium.com/faun/dry-helm-charts-for-micro-services-db3a1d6ecb80



### Cleaning up values

First of all, we should consider reducing overwrites and solidify the defaults (see "Consider the removal of greymatter*.yaml files" section).

Secondly, we have mixed variable names at the moment(some camel case, some separated with underscore or hyphen). It may be a good idea to establish a standard. I was not sure about the subsection each subchart's `values.yaml` has. While it is easier to see the separation between `global` and its own scope (e.g. `control`), it will have be referred from the parent chart as `.Values.control.control.envvars` because it already appends the sub chart name. Neither seems ideal, but it may be good for us to come up with our conventions on them.    

https://helm.sh/docs/topics/chart_best_practices/values/

> NAMING CONVENTIONS
>
> Variables names should begin with a lowercase letter, and words should be separated with camelcase
>
> DOCUMENT `VALUES.YAML`
>
> Every defined property in `values.yaml` should be documented. The documentation string should begin with the name of the property that it describes, and then give at least a one-sentence description.

Lastly, we have `gen-docs.py` which creates a table of variables. If each variable had a single sentence right above it, it would be even simpler to add a description of the value into the table (currently the column is there but blank).

**Comment by kaitmore** [comment]
@hiromis 

I had an idea for the `greymatter/requirements` file to avoid having to manually change the file every time we need to review a PR. What if we combine the requirements-dev and requirements files so there are two entries for each service, but they have conditions so when global.dev=true it uses local charts:

```
dependencies:
  - name: catalog
    repository: 'file://../catalog'
    version: '2.1.6'
    condition: global.dev

  - name: catalog
    version: '2.1.6'
    repository: 'https://nexus.production.deciphernow.com/repository/helm-hosted'
    condition: global.prod
```
We could then add a new make command for dev that sets this flag, e.g.:

```
helm install greymatter --set global.dev=true -n gm-deploy
```

https://v2.helm.sh/docs/chart_best_practices/#conditions-and-tags

**Comment by tilleryd** [comment]
Some of these problems can be helped by proper semver and clear changelogs that identfy breaking changes.

**Comment by tilleryd** [comment]
We should also explore [dhall-kubernetes](https://github.com/dhall-lang/dhall-kubernetes). Dhall is a configuration programming language that can be used to generate YAML.

**Comment by chrismholmes** [comment]
Take the brainstorming in this thread and build an actionable proposal.  Here is the template we will begin to use internally and/or externally.

https://gist.github.com/alecholmez/fa34dbe94b278defb9c2e46b40acb044

**Comment by hiromis** [comment]
Created a proposal under the greymatter repo:
https://github.com/DecipherNow/greymatter/issues/254
