### ISSUE TITLE
Ensure our helm charts support k8 version 1.11 (openshift support)

### ISSUE THREAD

**Issue by moosecanswim** [DecipherNow/helm-charts#623]
Some of our customers use an environment with 1.11 and we need our helm charts to be deployable into those environments.  

When deploying fabric i got this error
```
helm install fabric decipher/fabric-gov --set=global.waiter.service_account.create=false -f di2e-fabric-values.yaml -f ../global.yaml
Error: Deployment in version "v1" cannot be handled as a Deployment: v1.Deployment.Spec: v1.DeploymentSpec.Template: v1.PodTemplateSpec.Spec: v1.PodSpec.Containers: []v1.Container: v1.Container.Env: []v1.EnvVar: v1.EnvVar.Value: ReadString: expects " or n, but found 3, error found in #10 byte of ...|,"value":3000}],"ima|..., bigger context ...|EL","value":"info"},{"name":"HTTPS_PORT","value":3000}],"image":"docker-greymatter.di2e.net/greymatt|...
```

**Comment by chrisbsmith** [comment]
@justincely @joshua-rutherford @tilleryd this is a high priority issue. This will prevent us from deploying to di2e, which is running openshift 3.11

**Comment by tilleryd** [comment]
I propose that we upgrade to the latest version possible rather than 1.11, as long as its backwards compatible with 1.11.

**Comment by moosecanswim** [comment]
I was testing installing aac on a k3d cluster and had to make a few changes to the deployment before it would deploy because the k8 api had changed between 1.11 and 1.15.

**Comment by chrisbsmith** [comment]
@tilleryd the issue is that as k8s continues to move forward, the APIs change and what's available at each API do also.  Kubernetes 1.16 deprecated a lot of APIs, for example:

`Deployment in the extensions/v1beta1, apps/v1beta1, and apps/v1beta2 API versions is no longer served`

They created a page to list the deprecated APIs: https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/ .  We may have to draw a line in the sand and provide charts that support kubernetes versions <1.16 and ones that support newer.  This is how cert-manager has done it in the past.

The hard part here is that OpenShift 3.11 is hard wired to Kubernetes 3.11.  As long as our customers run OpenShift 3.11, we'll have to support it.

**Comment by moosecanswim** [comment]
This is the debug

**Comment by moosecanswim** [comment]
Looks like jwt is expecting https_port and that value is not getting added.  looking into it.  Hopefully that is the root of the issue as that would be an easy fix.

**Comment by moosecanswim** [comment]
Found to be the core issue.
kubernetes 1.11 does not seem to be able to handle an envar which is not a string. 
Deployed jwt manually with:
```
### FAILS
- name: HTTPS_PORT
  value: 3000
```

```
### WORKS
- name: HTTPS_PORT
  value: "3000"
```

**Comment by moosecanswim** [comment]
https://github.com/DecipherNow/helm-charts/pull/624 adds quotes to jwt-gov... the jwt chart already had them so there was just a divergence at some point

**Comment by justincely** [comment]
@chrisbsmith @moosecanswim is this g2g?  can close?

**Comment by moosecanswim** [comment]
Yeah, we can close this
